### ISSUE TITLE
Photo Translate Example not working

### ISSUE THREAD

**Issue by minkiapps** [HMS-Core/hms-ml-demo#21]
I am trying to run the photo translate example on my Huawei Mate 30 Pro...

- I setup my own agconnect-services.json and use the correct application id.
- I enabled ML Kit API on my developer console 

Everytime I hit the translate button, I get following exception from textAnalyzer: `com.huawei.hms.mlsdk.common.MLException: UrlList is empty, failed to detect cloud text`.

**Comment by HMS-MLKit** [comment]
Please refer to this: https://github.com/HMS-Core/hms-ml-demo/pull/23/commits/dd63b3aa214b13aff7561a2d5284f15a4b9e7936

**Comment by minkiapps** [comment]
Thank you, it is working now.
