### ISSUE TITLE
Proguard rules for MLTextAnalyzer

### ISSUE THREAD

**Issue by minkiapps** [HMS-Core/hms-ml-demo#22]
If I turn on obfuscation, which is critically required since all my apps are obfuscated, the text analyser stops recognising any text...

Could you provide Proguard rules?

**Comment by Mike-mei** [comment]
@minkiapps About proguard rules, you can refer to this [documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/ml-configuringobfuscation-scripts-4)

**Comment by minkiapps** [comment]
thanks, working now...
Do you think the rules can be more fine grained? Since the purpose of Proguard is actually to obfuscate and optimise as much code as possible.
Also I think it would be good if the Proguard rules can be packaged directly in library, so developer don't need to bother with that themselves.

**Comment by Mike-mei** [comment]
Thank you for your advice.
