### ISSUE TITLE
ML-Kit Text: Chinese OCR not working 

### ISSUE THREAD

**Issue by minkiapps** [HMS-Core/hms-ml-demo#24]
I am trying to use the offline Chinese text recognition on my Google Pixel 2 XL, it is not working.
I have HMS Core installed on my device. (Version: 5.0.1.313)

This is the code how I initialise MLTextAnalyser:
```
private val hmsTextRecognizer : MLTextAnalyzer by lazy {
     val setting = MLLocalTextSetting.Factory()
         .setOCRMode(MLLocalTextSetting.OCR_DETECT_MODE)
         .setLanguage("zh")
         .create()
     MLAnalyzerFactory.getInstance().getLocalTextAnalyzer(setting)
}
```

The TextAnalyser doesn't recognise any text.
I see following error:

> E/CountryCodeBean: getVendorCountry=UNKNOWN
> E/CountryCodeBean: getSimCountryCode by not enableNetwork, countryCode=at
> E/CountryCodeBean: getVendorCountry=UNKNOWN
> E/CountryCodeBean: getSimCountryCode by not enableNetwork, countryCode=at
> E/HaLogProvider: forbiddenHiLog.getVenderCountry=UNKNOWN
> E/HaLogProvider: forbiddenHiLog openHa = false
> E/FocusShootOCREngine: ocr load model failed
> E/HaLogProvider: forbiddenHiLog.getVenderCountry=UNKNOWN
> E/HaLogProvider: forbiddenHiLog openHa = false

On my Huawei Mate 30 Pro it works.

**Comment by Mike-mei** [comment]
@minkiapps What is the text dependencies that you integrate in build.gradle?

**Comment by minkiapps** [comment]
Thanks for asking, I just realised I didn't include 
`implementation 'com.huawei.hms:ml-computer-vision-ocr-cn-model:2.0.1.300'`
I wasn't paying attention because seems like on my Huawei Mate 30 Pro it works without it...

This issue can be closed.

I have another question, I see in the documentation that ML-Kit TTS is only available on Huawei phone, will it be sometime also available on non Huawei phones (but with HMS core installed)?

**Comment by Mike-mei** [comment]
TTS is only available on Huawei phone now, non Huawei phones are temporarily unavailable, but we will consider your suggestions.
