### ISSUE TITLE
tv横屏的轮廓点是反的 ，如何处理 ？

### ISSUE THREAD

**Issue by mmm2016** [HMS-Core/hms-ml-demo#57]

**Comment by Mike-mei** [comment]
你好，可以把问题描述的更具体一些吗？
比如使用了ML Kit的哪个能力，测试环境/设备是什么，日志文件，截图等等
这样方便我们进行问题定位。

**Comment by mmm2016** [comment]
非常感谢你的回复 ，就是我使用人脸轮廓点 ，把竖屏强制改为横屏，因为电视设备是横屏的，这个时候贴纸特征点什么的是反的 。我已经自己分析解决了 。

**Comment by Mike-mei** [comment]
好的，感谢您对华为机器学习服务的支持
