### ISSUE TITLE
Is this compatible in Google Play Store?

### ISSUE THREAD

**Issue by kyygit** [HMS-Core/hms-ml-demo#69]
probably i am asking a noob question.
Can the HMS-integrated app, be published in Google Play Store? 
(for example, i am using the Face Detection feature from the HMS-Core)

**Comment by Mike-mei** [comment]
The apps can be published in Google Play Store, but actually it depends on the requirements of the app store review guide. For example, different App store has different requirements for In-App Purchase Kit.

**Comment by kyygit** [comment]
thanks for your reminder of the in-app purchase kit.
but i would only use the face detection thingy, so probably it would not be a concern right? :)
