### ISSUE TITLE
关于Face2D-Sticker的问题

### ISSUE THREAD

**Issue by MRDHR** [HMS-Core/hms-ml-demo#71]
测试过Face2D-Sticker demo后，预览和贴纸是竖屏的，在修改activity为横屏后特征点和贴纸均横向显示，请问如何修改才能达到横向预览并且特征点和贴纸也正确显示？

目前表现：
![QQ图片20210112174156](https://user-images.githubusercontent.com/5576916/104297170-803ef200-54fd-11eb-8685-56268e23f399.png)

期望结果：
![QQ图片20210112174348](https://user-images.githubusercontent.com/5576916/104297362-bed4ac80-54fd-11eb-960b-dc1d6e19992f.png)

灵魂画图 请见谅，
![image](https://user-images.githubusercontent.com/5576916/104297394-c6945100-54fd-11eb-8382-7a16a494e282.png)

**Comment by Mike-mei** [comment]
若要实现特征点和贴纸也正确显示，需要修改EGLCameral类，getRotationAngleZ 的角度 -180
重新计算x ,y 的值
```float x = ( point.getX() / width) * 2 - 1```
```float y = 1-( point.getY() / height ) * 2```

**Comment by MRDHR** [comment]
修改后确实可行，谢谢大佬回复。
